--liquibase formatted sql
create table menu (
                      id bigint generated by default as identity,
                      name varchar(255),
                      primary key (id)
);
create table recipe (
                        id bigint generated by default as identity,
                        calories double not null,
                        carbs double not null,
                        cooking_time integer not null,
                        description varchar(255),
                        description_short varchar(255),
                        fat double not null,
                        weight double not null default 0,
                        count int not null default 0,
                        name varchar(255),
                        protein double not null,
                        menu_id bigint,
                        primary key (id),
                        foreign key (menu_id) references menu
);

create table recipe_parents_recipe (
                                       child_recipe_id bigint not null,
                                       parents_recipe_id bigint not null,
                                       primary key (child_recipe_id, parents_recipe_id),
                                       foreign key (parents_recipe_id) references recipe,
                                       foreign key (child_recipe_id) references recipe
);

create table tag (
                     id bigint generated by default as identity,
                     name varchar(255),
                     primary key (id)
);

create table tag_recipes (
                             tag_id bigint not null,
                             recipes_id bigint not null,
                             primary key (tag_id, recipes_id),
                             foreign key (recipes_id) references recipe,
                             foreign key (tag_id) references tag
);



